/* ===========================================================================
   CO2 Emissions Explorer

   Everything here runs against `data/co2.json`, which is generated by
   `scripts/export_web_data.py` from the same Excel panel and the same fitted
   coefficients the Streamlit app uses. The prediction below is the identical
   arithmetic: intercept + sum(coefficient * input).
   =========================================================================== */

const SVG_NS = 'http://www.w3.org/2000/svg';

const SERIES = {
  WY: { name: 'Wyoming', varName: '--series-wy' },
  ND: { name: 'North Dakota', varName: '--series-nd' },
  AK: { name: 'Alaska', varName: '--series-ak' },
};

const ORDER = ['WY', 'ND', 'AK'];

const state = {
  data: null,
  activeState: 'WY',
  inputs: {},
  charts: [],
};

/* ── Small helpers ────────────────────────────────────────────────────── */

const el = (tag, attrs = {}, text) => {
  const node = document.createElement(tag);
  for (const [key, value] of Object.entries(attrs)) {
    if (key === 'class') node.className = value;
    else if (key === 'style') node.style.cssText = value;
    else node.setAttribute(key, value);
  }
  // textContent, never innerHTML: series names come from a data file
  if (text != null) node.textContent = text;
  return node;
};

const svg = (tag, attrs = {}, text) => {
  const node = document.createElementNS(SVG_NS, tag);
  for (const [key, value] of Object.entries(attrs)) node.setAttribute(key, value);
  if (text != null) node.textContent = text;
  return node;
};

const cssVar = (name) => getComputedStyle(document.documentElement).getPropertyValue(name).trim();

const seriesColor = (code) => cssVar(SERIES[code].varName);

const clamp = (value, low, high) => Math.min(high, Math.max(low, value));

/** Round tonnes to one decimal, the precision the source data carries. */
const fmtTonnes = (value) => value.toFixed(1);

const fmtSigned = (value) => (value >= 0 ? '+' : '−') + Math.abs(value).toFixed(1);

/**
 * Compact notation for the large engineering inputs (20.00M, 38.5K).
 * The threshold sits at 1,000 rather than 10,000 so both ends of a slider's
 * scale use the same notation instead of reading "5,192" against "42.1K".
 */
const fmtCompact = (value) => {
  const abs = Math.abs(value);
  if (abs >= 1e9) return (value / 1e9).toFixed(2) + 'B';
  if (abs >= 1e6) return (value / 1e6).toFixed(2) + 'M';
  if (abs >= 1e3) return (value / 1e3).toFixed(1) + 'K';
  return Math.round(value).toLocaleString('en-US');
};

const prefersReducedMotion = () =>
  window.matchMedia('(prefers-reduced-motion: reduce)').matches;

/* ── Scales ───────────────────────────────────────────────────────────── */

const linearScale = (domain, range) => {
  const [d0, d1] = domain;
  const [r0, r1] = range;
  const span = d1 - d0 || 1;
  return (value) => r0 + ((value - d0) / span) * (r1 - r0);
};

/** Tick values at a readable interval covering [0, max]. */
const niceTicks = (max, count = 5) => {
  const raw = max / count;
  const magnitude = Math.pow(10, Math.floor(Math.log10(raw)));
  const normalized = raw / magnitude;
  const step = (normalized >= 5 ? 10 : normalized >= 2 ? 5 : normalized >= 1 ? 2 : 1) * magnitude;
  const ticks = [];
  for (let v = 0; v <= max + step * 0.001; v += step) ticks.push(Number(v.toFixed(6)));
  return ticks;
};

/* ── Responsive chart host ────────────────────────────────────────────── */

/**
 * Re-renders `draw` at the container's true pixel width, so SVG text stays at
 * its intended size instead of being scaled by a viewBox.
 */
const mountChart = (container, draw) => {
  if (!container) return;
  let lastWidth = 0;

  const render = (width) => {
    if (width < 60) return;
    container.replaceChildren(draw(width));
  };

  const observer = new ResizeObserver((entries) => {
    for (const entry of entries) {
      const width = Math.round(entry.contentRect.width);
      if (Math.abs(width - lastWidth) < 2) continue;
      lastWidth = width;
      render(width);
    }
  });

  observer.observe(container);
  state.charts.push(() => render(container.clientWidth || lastWidth));
};

const redrawAllCharts = () => {
  for (const redraw of state.charts) redraw();
};

/* ── Tooltip ──────────────────────────────────────────────────────────── */

const tooltip = {
  node: document.getElementById('tooltip'),

  show(x, y, title, rows) {
    const node = this.node;
    node.replaceChildren();
    node.appendChild(el('p', { class: 'tooltip-title' }, title));

    for (const row of rows) {
      const line = el('div', { class: 'tooltip-row' });
      if (row.color) {
        line.appendChild(el('span', { class: 'tooltip-key', style: `background:${row.color}` }));
      }
      line.appendChild(el('span', { class: 'tooltip-name' }, row.name));
      line.appendChild(el('span', { class: 'tooltip-value' }, row.value));
      node.appendChild(line);
    }

    node.hidden = false;

    // Keep the panel inside the viewport on both axes.
    const box = node.getBoundingClientRect();
    const left = clamp(x + 16, 8, window.innerWidth - box.width - 8);
    const top = clamp(y - box.height - 14, 8, window.innerHeight - box.height - 8);
    node.style.left = `${left}px`;
    node.style.top = `${top}px`;
  },

  hide() {
    this.node.hidden = true;
  },
};

/* ── Chart: the 2023 spread across all fifty states ───────────────────── */

const drawSpread = (width) => {
  const { spread, national } = state.data;
  const values = spread.values;

  const margin = { top: 34, right: 22, bottom: 40, left: 22 };
  const plotWidth = width - margin.left - margin.right;
  const radius = plotWidth < 420 ? 3.6 : 4.6;
  const maxValue = Math.max(...values.map((d) => d.value));

  const x = linearScale([0, maxValue * 1.04], [margin.left, margin.left + plotWidth]);

  // Deterministic beeswarm: walk the sorted values and drop each dot into the
  // nearest free vertical slot, so dense low-emission states stack instead of
  // hiding one another. Offsets are computed around zero and normalised
  // afterwards, so however deep the stack gets, the labels above the topmost
  // dot always have room.
  const gap = radius * 2 + 1.2;
  const placed = [];

  for (const point of [...values].sort((a, b) => a.value - b.value)) {
    const cx = x(point.value);
    let offset = 0;
    for (let k = 0; k < 24; k += 1) {
      const candidates = k === 0 ? [0] : [k, -k];
      let found = false;
      for (const step of candidates) {
        const testY = step * gap;
        const collides = placed.some(
          (p) => (p.cx - cx) ** 2 + (p.offset - testY) ** 2 < (gap * 0.98) ** 2
        );
        if (!collides) {
          offset = testY;
          found = true;
          break;
        }
      }
      if (found) break;
    }
    placed.push({ ...point, cx, offset });
  }

  // Lay the three direct labels out before anything is positioned vertically.
  // Wyoming, North Dakota and Alaska sit close together on a narrow screen, so
  // labels are stacked into tiers whenever their text would collide, and the
  // state code stands in for the full name once the panel gets tight.
  const useCodes = plotWidth < 460;
  const tierHeight = 32;
  const tierEnds = [];

  const labelDefs = ORDER.map((code) => {
    const point = values.find((v) => v.state === code);
    const text = useCodes ? code : SERIES[code].name;
    const sub = `${fmtTonnes(point.value)} t`;
    return { code, value: point.value, cx: x(point.value), text, sub };
  })
    .sort((a, b) => a.cx - b.cx)
    .map((def) => {
      const textWidth = Math.max(def.text.length * 7.1, def.sub.length * 6.8);
      const left = def.cx - textWidth / 2;
      const right = def.cx + textWidth / 2;
      let tier = 0;
      while (tierEnds[tier] != null && left < tierEnds[tier] + 10) tier += 1;
      tierEnds[tier] = right;
      return { ...def, tier, textWidth };
    });

  const maxTier = Math.max(...labelDefs.map((d) => d.tier));

  // Reserve space above the highest dot for the label tiers and the median tag
  const topPadding = margin.top + 46 + maxTier * tierHeight;
  const minOffset = Math.min(...placed.map((p) => p.offset));
  const shift = topPadding - minOffset;
  for (const point of placed) point.cy = point.offset + shift;

  const minY = Math.min(...placed.map((p) => p.cy));
  const maxY = Math.max(...placed.map((p) => p.cy));
  const axisY = maxY + 34;
  const height = axisY + margin.bottom;

  const root = svg('svg', {
    viewBox: `0 0 ${width} ${height}`,
    width,
    height,
    role: 'img',
    'aria-label': `Dot plot of per-capita CO2 for all 50 states in ${spread.year}. Values run from ${values[0].value} tonnes to ${values[values.length - 1].value} tonnes per person.`,
  });

  // Axis
  root.appendChild(
    svg('line', { class: 'axis-line', x1: margin.left, y1: axisY, x2: margin.left + plotWidth, y2: axisY })
  );

  for (const tick of niceTicks(maxValue, 5)) {
    const tx = x(tick);
    root.appendChild(svg('line', { class: 'grid-line', x1: tx, y1: minY - 18, x2: tx, y2: axisY }));
    root.appendChild(
      svg('text', { class: 'axis-text', x: tx, y: axisY + 17, 'text-anchor': 'middle' }, String(tick))
    );
  }
  root.appendChild(
    svg(
      'text',
      { class: 'axis-text', x: margin.left + plotWidth, y: axisY + 33, 'text-anchor': 'end' },
      'tonnes per person per year'
    )
  );

  // Median marker: chrome, not a series
  const medianValue = national.median[national.median.length - 1];
  const medianX = x(medianValue);
  root.appendChild(
    svg('line', {
      class: 'reference-line',
      x1: medianX,
      y1: minY - 22,
      x2: medianX,
      y2: axisY,
    })
  );
  root.appendChild(
    svg(
      'text',
      { class: 'end-label-sub', x: medianX, y: minY - 28, 'text-anchor': 'middle' },
      `median ${fmtTonnes(medianValue)}`
    )
  );

  const muted = cssVar('--ink-muted');
  const surface = cssVar('--bg-elevated');

  for (const point of placed) {
    const highlighted = ORDER.includes(point.state);
    const color = highlighted ? seriesColor(point.state) : muted;

    const dot = svg('circle', {
      class: 'spread-dot',
      cx: point.cx,
      cy: point.cy,
      r: highlighted ? radius + 1.6 : radius,
      fill: color,
      'fill-opacity': highlighted ? 1 : 0.42,
    });
    if (highlighted) {
      dot.setAttribute('stroke', surface);
      dot.setAttribute('stroke-width', '2');
    }
    root.appendChild(dot);

    // Hit area comfortably larger than the mark itself
    const hit = svg('circle', { class: 'spread-hit', cx: point.cx, cy: point.cy, r: Math.max(12, radius + 8) });
    const label = point.name || point.state;
    hit.setAttribute('tabindex', '0');
    hit.setAttribute('role', 'img');
    hit.setAttribute('aria-label', `${label}, ${fmtTonnes(point.value)} tonnes per person`);

    const reveal = (event) => {
      const box = hit.getBoundingClientRect();
      tooltip.show(box.left + box.width / 2, box.top + box.height / 2, String(spread.year), [
        { color, name: label, value: `${fmtTonnes(point.value)} t` },
      ]);
      dot.setAttribute('r', String((highlighted ? radius + 1.6 : radius) + 2));
      if (event && event.type === 'focus') hit.scrollIntoView({ block: 'nearest', inline: 'nearest' });
    };
    const conceal = () => {
      tooltip.hide();
      dot.setAttribute('r', String(highlighted ? radius + 1.6 : radius));
    };

    hit.addEventListener('pointerenter', reveal);
    hit.addEventListener('pointerleave', conceal);
    hit.addEventListener('focus', reveal);
    hit.addEventListener('blur', conceal);
    root.appendChild(hit);
  }

  // Direct labels on the three case studies, so identity never rests on colour.
  // Each sits in the tier assigned above, with a leader down to its own dot.
  for (const def of labelDefs) {
    const point = placed.find((p) => p.state === def.code);
    if (!point) continue;

    const baseY = point.cy - radius - 12;
    const labelY = baseY - def.tier * tierHeight;

    // Keep the text inside the panel at either edge
    let anchor = 'middle';
    if (def.cx + def.textWidth / 2 > margin.left + plotWidth) anchor = 'end';
    else if (def.cx - def.textWidth / 2 < margin.left) anchor = 'start';

    if (def.tier > 0) {
      root.appendChild(
        svg('line', {
          class: 'leader-line',
          x1: def.cx,
          y1: labelY + 5,
          x2: def.cx,
          y2: point.cy - radius - 3,
        })
      );
    }

    root.appendChild(
      svg('text', { class: 'end-label', x: def.cx, y: labelY, 'text-anchor': anchor }, def.text)
    );
    root.appendChild(
      svg('text', { class: 'end-label-sub', x: def.cx, y: labelY - 14, 'text-anchor': anchor }, def.sub)
    );
  }

  return root;
};

/* ── Chart: 1998 to 2023 trend for the three case studies ─────────────── */

const drawTrend = (width) => {
  const { cases, national } = state.data;
  const years = cases.WY.years;

  const compact = width < 620;
  const margin = { top: 18, right: compact ? 20 : 132, bottom: 40, left: 44 };
  const height = compact ? 320 : 380;
  const plotWidth = width - margin.left - margin.right;
  const plotHeight = height - margin.top - margin.bottom;

  const maxValue = Math.max(...ORDER.flatMap((code) => cases[code].co2));
  const x = linearScale([years[0], years[years.length - 1]], [margin.left, margin.left + plotWidth]);
  const y = linearScale([0, maxValue * 1.06], [margin.top + plotHeight, margin.top]);

  const root = svg('svg', {
    viewBox: `0 0 ${width} ${height}`,
    width,
    height,
    role: 'img',
    'aria-label':
      'Line chart of per-capita CO2 from 1998 to 2023 for Wyoming, North Dakota and Alaska, with the national median for scale. Full values are available in the table view.',
  });

  // Gridlines and y axis
  for (const tick of niceTicks(maxValue * 1.06, 5)) {
    const ty = y(tick);
    root.appendChild(
      svg('line', { class: 'grid-line', x1: margin.left, y1: ty, x2: margin.left + plotWidth, y2: ty })
    );
    root.appendChild(
      svg('text', { class: 'axis-text', x: margin.left - 10, y: ty + 4, 'text-anchor': 'end' }, String(tick))
    );
  }

  // x axis
  const axisY = margin.top + plotHeight;
  root.appendChild(
    svg('line', { class: 'axis-line', x1: margin.left, y1: axisY, x2: margin.left + plotWidth, y2: axisY })
  );
  const tickYears = years.filter((yr) => yr % 5 === 0 || yr === years[years.length - 1]);
  for (const yr of tickYears) {
    root.appendChild(
      svg('text', { class: 'axis-text', x: x(yr), y: axisY + 20, 'text-anchor': 'middle' }, String(yr))
    );
  }
  root.appendChild(
    svg('text', { class: 'axis-text', x: margin.left - 10, y: margin.top - 6, 'text-anchor': 'end' }, 't')
  );

  const path = (points) => points.map((p, i) => `${i === 0 ? 'M' : 'L'}${p[0].toFixed(2)},${p[1].toFixed(2)}`).join(' ');

  // National median: reference chrome, drawn first so series sit above it
  const medianPoints = years.map((yr, i) => [x(yr), y(national.median[national.years.indexOf(yr)] ?? national.median[i])]);
  root.appendChild(svg('path', { class: 'reference-line', d: path(medianPoints) }));

  const seriesPaths = {};
  for (const code of ORDER) {
    const color = seriesColor(code);
    const points = cases[code].co2.map((value, i) => [x(years[i]), y(value)]);
    const line = svg('path', { class: 'series-line', d: path(points), stroke: color });
    root.appendChild(line);
    seriesPaths[code] = points;
  }

  // Direct end labels. North Dakota and Alaska finish about 10 t apart, which
  // is closer than a two-line label block is tall, so labels are spread to a
  // minimum spacing and any label that moved gets a leader back to its line.
  if (!compact) {
    const endX = margin.left + plotWidth + 12;
    const minGap = 32;

    const labels = ORDER.map((code) => {
      const last = cases[code].co2[cases[code].co2.length - 1];
      return { anchorY: y(last), y: y(last), name: SERIES[code].name, value: `${fmtTonnes(last)} t` };
    }).sort((a, b) => a.anchorY - b.anchorY);

    // Push down through the stack, then back up if the last one overshot
    for (let i = 1; i < labels.length; i += 1) {
      if (labels[i].y - labels[i - 1].y < minGap) labels[i].y = labels[i - 1].y + minGap;
    }
    const bottomLimit = margin.top + plotHeight - 6;
    if (labels[labels.length - 1].y > bottomLimit) {
      labels[labels.length - 1].y = bottomLimit;
      for (let i = labels.length - 2; i >= 0; i -= 1) {
        if (labels[i + 1].y - labels[i].y < minGap) labels[i].y = labels[i + 1].y - minGap;
      }
    }

    for (const label of labels) {
      if (Math.abs(label.y - label.anchorY) > 1.5) {
        root.appendChild(
          svg('polyline', {
            class: 'leader-line',
            fill: 'none',
            points: `${endX - 11},${label.anchorY} ${endX - 6},${label.anchorY} ${endX - 4},${label.y - 4} ${endX - 1},${label.y - 4}`,
          })
        );
      }
      root.appendChild(svg('text', { class: 'end-label', x: endX, y: label.y - 2 }, label.name));
      root.appendChild(svg('text', { class: 'end-label-sub', x: endX, y: label.y + 13 }, label.value));
    }

    const medianLast = national.median[national.median.length - 1];
    root.appendChild(
      svg('text', { class: 'end-label-sub', x: endX, y: y(medianLast) + 4 }, `median ${fmtTonnes(medianLast)}`)
    );
  }

  // Hover layer: the crosshair finds the year, the tooltip lists every series
  const crosshair = svg('line', {
    class: 'crosshair',
    x1: margin.left,
    x2: margin.left,
    y1: margin.top,
    y2: axisY,
    opacity: 0,
  });
  root.appendChild(crosshair);

  const dots = ORDER.map((code) => {
    const dot = svg('circle', {
      class: 'focus-dot',
      r: 4.5,
      fill: seriesColor(code),
      opacity: 0,
    });
    root.appendChild(dot);
    return { code, dot };
  });

  const surface = cssVar('--bg-elevated');
  for (const item of dots) item.dot.setAttribute('stroke', surface);

  let activeIndex = -1;

  const moveTo = (index, clientX, clientY) => {
    if (index < 0 || index >= years.length) return;
    activeIndex = index;
    const year = years[index];
    const px = x(year);

    crosshair.setAttribute('x1', px);
    crosshair.setAttribute('x2', px);
    crosshair.setAttribute('opacity', '0.7');

    for (const item of dots) {
      const py = seriesPaths[item.code][index][1];
      item.dot.setAttribute('cx', px);
      item.dot.setAttribute('cy', py);
      item.dot.setAttribute('opacity', '1');
    }

    const rows = ORDER.map((code) => ({
      color: seriesColor(code),
      name: SERIES[code].name,
      value: `${fmtTonnes(cases[code].co2[index])} t`,
    }));
    const medianIndex = national.years.indexOf(year);
    if (medianIndex >= 0) {
      rows.push({ color: cssVar('--axis'), name: 'National median', value: `${fmtTonnes(national.median[medianIndex])} t` });
    }

    let anchorX = clientX;
    let anchorY = clientY;
    if (anchorX == null) {
      const box = root.getBoundingClientRect();
      anchorX = box.left + (px / width) * box.width;
      anchorY = box.top + box.height / 2;
    }
    tooltip.show(anchorX, anchorY, String(year), rows);
  };

  const clear = () => {
    crosshair.setAttribute('opacity', '0');
    for (const item of dots) item.dot.setAttribute('opacity', '0');
    tooltip.hide();
  };

  const hit = svg('rect', {
    class: 'hit-area',
    x: margin.left,
    y: margin.top,
    width: Math.max(plotWidth, 1),
    height: plotHeight,
    tabindex: '0',
    role: 'application',
    'aria-label': 'Year by year readout. Use the left and right arrow keys to step through years.',
  });

  hit.addEventListener('pointermove', (event) => {
    const box = root.getBoundingClientRect();
    const scale = width / box.width;
    const localX = (event.clientX - box.left) * scale;
    const ratio = (localX - margin.left) / plotWidth;
    const index = clamp(Math.round(ratio * (years.length - 1)), 0, years.length - 1);
    moveTo(index, event.clientX, box.top + margin.top);
  });
  hit.addEventListener('pointerleave', clear);
  hit.addEventListener('blur', clear);
  hit.addEventListener('focus', () => moveTo(activeIndex < 0 ? years.length - 1 : activeIndex));
  hit.addEventListener('keydown', (event) => {
    if (event.key === 'ArrowRight') {
      event.preventDefault();
      moveTo(Math.min(activeIndex + 1, years.length - 1));
    } else if (event.key === 'ArrowLeft') {
      event.preventDefault();
      moveTo(Math.max(activeIndex - 1, 0));
    } else if (event.key === 'Escape') {
      clear();
    }
  });

  root.appendChild(hit);
  return root;
};

/* ── Chart: holdout error, one small multiple per state ───────────────── */

const drawHoldout = (code) => (width) => {
  const holdout = state.data.cases[code].holdout;
  const rows = holdout.rows;

  const margin = { top: 16, right: 14, bottom: 26, left: 36 };
  const height = 168;
  const plotWidth = width - margin.left - margin.right;
  const plotHeight = height - margin.top - margin.bottom;

  const all = rows.flatMap((r) => [r.actual, r.predicted]);
  const low = Math.min(...all);
  const high = Math.max(...all);
  const pad = (high - low) * 0.28 || 1;

  const x = linearScale([0, rows.length - 1], [margin.left + 18, margin.left + plotWidth - 18]);
  const y = linearScale([low - pad, high + pad], [margin.top + plotHeight, margin.top]);

  const color = seriesColor(code);
  const surface = cssVar('--bg-elevated');

  const root = svg('svg', {
    viewBox: `0 0 ${width} ${height}`,
    width,
    height,
    role: 'img',
    'aria-label': `${SERIES[code].name} holdout test. ${rows
      .map((r) => `${r.year}: actual ${fmtTonnes(r.actual)}, predicted ${fmtTonnes(r.predicted)}`)
      .join('. ')}.`,
  });

  for (const tick of [low - pad * 0.2, (low + high) / 2, high + pad * 0.2].map((v) => Math.round(v))) {
    const ty = y(tick);
    root.appendChild(
      svg('line', { class: 'grid-line', x1: margin.left, y1: ty, x2: margin.left + plotWidth, y2: ty })
    );
    root.appendChild(
      svg('text', { class: 'axis-text', x: margin.left - 8, y: ty + 4, 'text-anchor': 'end' }, String(tick))
    );
  }

  rows.forEach((row, i) => {
    const px = x(i);
    const actualY = y(row.actual);
    const predictedY = y(row.predicted);

    // The gap is the error: draw it as the connecting segment
    root.appendChild(
      svg('line', {
        x1: px,
        y1: actualY,
        x2: px,
        y2: predictedY,
        stroke: color,
        'stroke-width': 2,
        'stroke-opacity': 0.35,
        'stroke-linecap': 'round',
      })
    );

    root.appendChild(
      svg('circle', { cx: px, cy: actualY, r: 4.5, fill: color, stroke: surface, 'stroke-width': 2 })
    );
    root.appendChild(
      svg('circle', {
        cx: px,
        cy: predictedY,
        r: 4.5,
        fill: surface,
        stroke: color,
        'stroke-width': 2,
      })
    );

    root.appendChild(
      svg(
        'text',
        { class: 'axis-text', x: px, y: margin.top + plotHeight + 19, 'text-anchor': 'middle' },
        String(row.year)
      )
    );

    const hit = svg('rect', {
      class: 'hit-area',
      x: px - 16,
      y: margin.top,
      width: 32,
      height: plotHeight,
      tabindex: '0',
      role: 'img',
      'aria-label': `${row.year}: actual ${fmtTonnes(row.actual)}, predicted ${fmtTonnes(row.predicted)}, error ${fmtSigned(row.error)}`,
    });

    const reveal = () => {
      const box = hit.getBoundingClientRect();
      tooltip.show(box.left + box.width / 2, box.top + 30, String(row.year), [
        { color, name: 'Actual', value: `${fmtTonnes(row.actual)} t` },
        { color: cssVar('--ink-muted'), name: 'Predicted', value: `${fmtTonnes(row.predicted)} t` },
        { name: 'Error', value: `${fmtSigned(row.error)} t` },
      ]);
    };
    hit.addEventListener('pointerenter', reveal);
    hit.addEventListener('pointerleave', () => tooltip.hide());
    hit.addEventListener('focus', reveal);
    hit.addEventListener('blur', () => tooltip.hide());
    root.appendChild(hit);
  });

  return root;
};

/* ── Legends ──────────────────────────────────────────────────────────── */

const renderTrendLegend = () => {
  const host = document.getElementById('legend-trend');
  if (!host) return;
  host.replaceChildren();

  for (const code of ORDER) {
    const item = el('span', { class: 'legend-item', role: 'listitem' });
    item.appendChild(el('span', { class: 'legend-key', style: `background:${seriesColor(code)}` }));
    item.appendChild(el('span', {}, SERIES[code].name));
    host.appendChild(item);
  }

  const reference = el('span', { class: 'legend-item', role: 'listitem' });
  reference.appendChild(el('span', { class: 'legend-key is-reference' }));
  reference.appendChild(el('span', {}, 'National median'));
  host.appendChild(reference);
};

const renderSpreadLegend = () => {
  const host = document.getElementById('legend-spread');
  if (!host) return;
  host.replaceChildren();

  for (const code of ORDER) {
    const item = el('span', { class: 'legend-item', role: 'listitem' });
    item.appendChild(
      el('span', { class: 'legend-dot is-filled', style: `background:${seriesColor(code)};border-color:${seriesColor(code)}` })
    );
    item.appendChild(el('span', {}, SERIES[code].name));
    host.appendChild(item);
  }

  const other = el('span', { class: 'legend-item', role: 'listitem' });
  const muted = cssVar('--ink-muted');
  other.appendChild(
    el('span', { class: 'legend-dot is-filled', style: `background:${muted};border-color:${muted};opacity:.45` })
  );
  other.appendChild(el('span', {}, 'Other 47 states'));
  host.appendChild(other);
};

const renderHoldoutLegend = () => {
  const host = document.getElementById('legend-holdout');
  if (!host) return;
  host.replaceChildren();

  const actual = el('span', { class: 'legend-item', role: 'listitem' });
  actual.appendChild(el('span', { class: 'legend-dot is-filled' }));
  actual.appendChild(el('span', {}, 'Actual'));

  const predicted = el('span', { class: 'legend-item', role: 'listitem' });
  predicted.appendChild(el('span', { class: 'legend-dot is-hollow' }));
  predicted.appendChild(el('span', {}, 'Predicted by the model'));

  host.append(actual, predicted);
};

/* ── Case study cards ─────────────────────────────────────────────────── */

const CASE_NOTES = {
  WY: 'Coal burned for electricity and a small, slowly urbanising population set the level. Nothing else clears significance.',
  ND: 'The only state of the three where consumer spending and both fossil inputs matter at once.',
  AK: 'Coal is irrelevant here. Spending, gas and urbanisation carry the whole model.',
};

const renderCaseCards = () => {
  const host = document.getElementById('case-cards');
  if (!host) return;
  host.replaceChildren();

  const meta = state.data.meta.feature_meta;

  for (const code of ORDER) {
    const info = state.data.cases[code];
    const card = el('article', { class: 'case-card reveal', style: `--case-color:${seriesColor(code)}` });

    card.appendChild(el('p', { class: 'case-rank' }, `Rank ${info.rank} nationally`));
    card.appendChild(el('h3', { class: 'case-name' }, info.name));

    const metrics = el('dl', { class: 'case-metrics' });
    const addMetric = (label, value) => {
      const group = el('div', { class: 'case-metric' });
      group.appendChild(el('dt', {}, label));
      group.appendChild(el('dd', {}, value));
      metrics.appendChild(group);
    };
    addMetric('Adjusted R²', info.fit.adj_r_squared.toFixed(2));
    addMetric('Holdout RMSE', `${info.holdout.rmse.toFixed(1)} t`);
    card.appendChild(metrics);

    const drivers = el('div', { class: 'case-drivers' });
    drivers.appendChild(el('h4', {}, 'Significant at the 5% level'));
    const list = el('ul', { class: 'driver-list' });
    for (const key of info.model.significant) {
      list.appendChild(el('li', { class: 'driver-tag' }, meta[key].short));
    }
    drivers.appendChild(list);
    card.appendChild(drivers);

    card.appendChild(el('p', { class: 'case-note' }, CASE_NOTES[code]));
    host.appendChild(card);
  }
};

/* ── Holdout cards ────────────────────────────────────────────────────── */

const renderHoldoutCards = () => {
  const host = document.getElementById('holdout-grid');
  if (!host) return;
  host.replaceChildren();

  for (const code of ORDER) {
    const info = state.data.cases[code];
    const holdout = info.holdout;

    const card = el('article', { class: 'holdout-card reveal' });
    card.appendChild(el('h3', {}, info.name));

    const direction =
      holdout.mean_signed_error > 0.5
        ? 'over-predicts every unseen year'
        : holdout.mean_signed_error < -0.5
          ? 'under-predicts every unseen year'
          : 'tracks the unseen years closely';

    card.appendChild(
      el(
        'p',
        { class: 'holdout-summary' },
        `RMSE ${holdout.rmse.toFixed(2)} t, which is ${Math.round(holdout.rmse_share_of_range * 100)}% of this state's observed range. It ${direction}.`
      )
    );

    const chart = el('div', { class: 'chart holdout-chart' });
    card.appendChild(chart);
    host.appendChild(card);

    mountChart(chart, drawHoldout(code));
  }
};

/* ── Table view ───────────────────────────────────────────────────────── */

const renderTrendTable = () => {
  const body = document.getElementById('trend-table-body');
  if (!body) return;
  body.replaceChildren();

  const { cases, national } = state.data;
  cases.WY.years.forEach((year, i) => {
    const row = el('tr');
    row.appendChild(el('th', { scope: 'row' }, String(year)));
    for (const code of ORDER) row.appendChild(el('td', {}, fmtTonnes(cases[code].co2[i])));
    const medianIndex = national.years.indexOf(year);
    row.appendChild(el('td', {}, medianIndex >= 0 ? fmtTonnes(national.median[medianIndex]) : 'n/a'));
    body.appendChild(row);
  });

  const toggle = document.getElementById('toggle-table');
  const wrap = document.getElementById('trend-table');
  toggle?.addEventListener('click', () => {
    const open = toggle.getAttribute('aria-expanded') === 'true';
    toggle.setAttribute('aria-expanded', String(!open));
    wrap.hidden = open;
    toggle.textContent = open ? 'Table view' : 'Hide table';
  });
};

/* ── Predictor ────────────────────────────────────────────────────────── */

const predict = (code, inputs) => {
  const model = state.data.cases[code].model;
  let total = model.intercept;
  for (const [key, coefficient] of Object.entries(model.coefficients)) {
    total += coefficient * (inputs[key] ?? 0);
  }
  return total;
};

const resetInputsToLatest = (code) => {
  const spec = state.data.cases[code].inputs;
  state.inputs = {};
  for (const item of spec) state.inputs[item.key] = item.default;
};

const renderStatePicker = () => {
  const host = document.getElementById('state-picker');
  if (!host) return;
  host.replaceChildren();

  ORDER.forEach((code) => {
    const button = el('button', {
      type: 'button',
      role: 'radio',
      'aria-checked': String(code === state.activeState),
      style: `--seg-color:${seriesColor(code)}`,
      tabindex: code === state.activeState ? '0' : '-1',
    });
    button.appendChild(el('span', { class: 'seg-dot' }));
    button.appendChild(document.createTextNode(SERIES[code].name));

    button.addEventListener('click', () => selectState(code));
    button.addEventListener('keydown', (event) => {
      const index = ORDER.indexOf(code);
      if (event.key === 'ArrowRight' || event.key === 'ArrowDown') {
        event.preventDefault();
        selectState(ORDER[(index + 1) % ORDER.length], true);
      } else if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') {
        event.preventDefault();
        selectState(ORDER[(index - 1 + ORDER.length) % ORDER.length], true);
      }
    });

    host.appendChild(button);
  });
};

const selectState = (code, focus = false) => {
  state.activeState = code;
  resetInputsToLatest(code);
  renderStatePicker();
  renderSliders();
  updateResult();
  if (focus) {
    const index = ORDER.indexOf(code);
    document.getElementById('state-picker')?.children[index]?.focus();
  }
};

const renderSliders = () => {
  const host = document.getElementById('slider-stack');
  if (!host) return;
  host.replaceChildren();

  const spec = state.data.cases[state.activeState].inputs;

  for (const item of spec) {
    const row = el('div', { class: 'slider-row' });
    const id = `input-${item.key.replace(/\s+/g, '-').toLowerCase()}`;

    const label = el('label', { for: id });
    label.appendChild(document.createTextNode(item.label));
    const readout = el('span', { class: 'slider-value', id: `${id}-value` });
    readout.textContent = fmtCompact(state.inputs[item.key]);
    label.appendChild(readout);
    row.appendChild(label);

    row.appendChild(el('p', { class: 'slider-help', id: `${id}-help` }, item.unit));

    const range = el('input', {
      type: 'range',
      id,
      min: String(item.min),
      max: String(item.max),
      step: String(item.step),
      value: String(state.inputs[item.key]),
      'aria-describedby': `${id}-help`,
    });

    range.addEventListener('input', () => {
      const value = Number(range.value);
      state.inputs[item.key] = value;
      readout.textContent = fmtCompact(value);
      updateResult();
    });

    row.appendChild(range);

    const scale = el('div', { class: 'slider-scale' });
    scale.appendChild(el('span', {}, fmtCompact(item.min)));
    scale.appendChild(el('span', {}, fmtCompact(item.max)));
    row.appendChild(scale);

    host.appendChild(row);
  }
};

const renderContributions = () => {
  const host = document.getElementById('contributions');
  if (!host) return;
  host.replaceChildren();

  const info = state.data.cases[state.activeState];
  const meta = state.data.meta.feature_meta;

  const terms = Object.entries(info.model.coefficients).map(([key, coefficient]) => ({
    key,
    short: meta[key].short,
    value: coefficient * (state.inputs[key] ?? 0),
    significant: info.model.significant.includes(key),
  }));

  const largest = Math.max(...terms.map((t) => Math.abs(t.value)), 1);

  for (const term of terms) {
    const row = el('div', { class: 'contrib-row' });

    const name = el('span', { class: 'contrib-label' }, term.short);
    if (!term.significant) {
      name.appendChild(el('span', { class: 'contrib-flag', title: 'Not significant at the 5% level' }, 'n.s.'));
    }
    row.appendChild(name);

    const track = el('div', { class: 'contrib-track' });
    const share = (Math.abs(term.value) / largest) * 50;
    const bar = el('span', {
      class: `contrib-bar ${term.value >= 0 ? 'is-up' : 'is-down'}`,
      style:
        term.value >= 0
          ? `left:50%;width:${share.toFixed(2)}%`
          : `right:50%;width:${share.toFixed(2)}%`,
    });
    track.appendChild(bar);
    row.appendChild(track);

    row.appendChild(el('span', { class: 'contrib-value' }, fmtSigned(term.value)));
    host.appendChild(row);
  }

  const note = document.getElementById('contribution-note');
  if (note) {
    note.textContent = `Baseline intercept ${fmtTonnes(info.model.intercept)} t. Terms marked n.s. are not statistically significant at the 5% level, so their contribution is not distinguishable from zero.`;
  }
};

const updateResult = () => {
  const code = state.activeState;
  const info = state.data.cases[code];
  const value = predict(code, state.inputs);

  const number = document.getElementById('result-number');
  if (number) number.textContent = fmtTonnes(value);

  const context = document.getElementById('result-context');
  if (context) {
    const latestYear = info.years[info.years.length - 1];
    const latestActual = info.co2[info.co2.length - 1];
    const delta = value - latestActual;

    context.replaceChildren();
    context.appendChild(document.createTextNode(`${info.name} recorded `));
    context.appendChild(el('strong', {}, `${fmtTonnes(latestActual)} t`));
    context.appendChild(document.createTextNode(` in ${latestYear}. This forecast sits `));
    context.appendChild(el('strong', {}, `${fmtSigned(delta)} t`));
    context.appendChild(document.createTextNode(' against it.'));
  }

  renderContributions();
};

/* ── Facts in the hero strip ──────────────────────────────────────────── */

const renderFacts = () => {
  const { meta, spread, national, cases } = state.data;
  const values = spread.values;
  const low = values[0];
  const high = values[values.length - 1];

  const facts = {
    observations: meta.observations.toLocaleString('en-US'),
    latestYear: String(spread.year),
    spreadRatio: (high.value / low.value).toFixed(1),
    spreadLow: `${low.name || low.state} ${fmtTonnes(low.value)}`,
    spreadHigh: `${high.name || high.state} ${fmtTonnes(high.value)}`,
    bestR2: Math.max(...ORDER.map((c) => cases[c].fit.adj_r_squared)).toFixed(2),
    worstRmse: Math.max(...ORDER.map((c) => cases[c].holdout.rmse)).toFixed(1),
    medianLatest: fmtTonnes(national.median[national.median.length - 1]),
  };

  for (const [key, value] of Object.entries(facts)) {
    for (const node of document.querySelectorAll(`[data-fact="${key}"]`)) {
      node.textContent = value;
    }
  }
};

/* ── Theme ────────────────────────────────────────────────────────────── */

const applyTheme = (theme) => {
  document.documentElement.setAttribute('data-theme', theme);
  const toggle = document.getElementById('theme-toggle');
  if (toggle) {
    const next = theme === 'dark' ? 'light' : 'dark';
    toggle.setAttribute('aria-label', `Switch to ${next} theme`);
    toggle.setAttribute('aria-pressed', String(theme === 'dark'));
  }
  // Series colours are theme-specific, and anything that baked one into an
  // inline style is now stale, so charts and colour-carrying markup repaint.
  if (state.data) {
    renderSpreadLegend();
    renderTrendLegend();
    renderCaseCards();
    renderStatePicker();
    for (const node of document.querySelectorAll('#case-cards .reveal')) {
      node.classList.add('is-visible');
    }
  }
  redrawAllCharts();
};

const setupTheme = () => {
  const toggle = document.getElementById('theme-toggle');
  toggle?.addEventListener('click', () => {
    const next = document.documentElement.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
    try {
      localStorage.setItem('co2-theme', next);
    } catch (e) {
      /* private mode: the choice simply will not persist */
    }
    applyTheme(next);
  });

  // Follow the OS while the viewer has not chosen for themselves
  window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', (event) => {
    let stored = null;
    try {
      stored = localStorage.getItem('co2-theme');
    } catch (e) {
      /* ignore */
    }
    if (!stored) applyTheme(event.matches ? 'dark' : 'light');
  });

  // Let a host page keep an embedded copy in sync with its own theme
  window.addEventListener('message', (event) => {
    const payload = event.data;
    if (payload && payload.type === 'set-theme' && (payload.theme === 'dark' || payload.theme === 'light')) {
      applyTheme(payload.theme);
    }
  });
};

/* ── Reveal on scroll ─────────────────────────────────────────────────── */

const setupReveal = () => {
  const targets = document.querySelectorAll('.reveal');

  if (prefersReducedMotion() || !('IntersectionObserver' in window)) {
    for (const node of targets) node.classList.add('is-visible');
    return;
  }

  const observer = new IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (!entry.isIntersecting) continue;
        entry.target.classList.add('is-visible');
        observer.unobserve(entry.target);
      }
    },
    { threshold: 0.12, rootMargin: '0px 0px -40px 0px' }
  );

  for (const node of targets) observer.observe(node);
};

/* ── Boot ─────────────────────────────────────────────────────────────── */

const showLoadError = (detail) => {
  for (const id of ['chart-spread', 'chart-trend']) {
    const host = document.getElementById(id);
    if (!host) continue;
    host.replaceChildren();
    const box = el('div', { class: 'chart-state' });
    const message = el('div');
    message.appendChild(el('p', {}, 'The dataset could not be loaded.'));
    const hint = el('p', { style: 'margin-top:8px' });
    hint.appendChild(document.createTextNode('Serve this folder over HTTP rather than opening the file directly, for example '));
    hint.appendChild(el('code', {}, 'npx serve web'));
    hint.appendChild(document.createTextNode('.'));
    message.appendChild(hint);
    if (detail) message.appendChild(el('p', { style: 'margin-top:8px;opacity:.7' }, detail));
    box.appendChild(message);
    host.appendChild(box);
  }
};

const showLoading = () => {
  for (const [id, height] of [['chart-spread', 190], ['chart-trend', 340]]) {
    const host = document.getElementById(id);
    if (host) host.appendChild(el('div', { class: 'skeleton', style: `height:${height}px` }));
  }
};

const init = async () => {
  setupTheme();
  showLoading();

  let payload;
  try {
    const response = await fetch('data/co2.json');
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    payload = await response.json();
  } catch (error) {
    showLoadError(String(error && error.message ? error.message : error));
    setupReveal();
    return;
  }

  state.data = payload;
  state.activeState = ORDER[0];
  resetInputsToLatest(state.activeState);

  renderFacts();
  renderSpreadLegend();
  renderTrendLegend();
  renderHoldoutLegend();
  renderCaseCards();
  renderHoldoutCards();
  renderTrendTable();
  renderStatePicker();
  renderSliders();
  updateResult();

  document.getElementById('chart-spread')?.replaceChildren();
  document.getElementById('chart-trend')?.replaceChildren();
  mountChart(document.getElementById('chart-spread'), drawSpread);
  mountChart(document.getElementById('chart-trend'), drawTrend);

  document.getElementById('reset-inputs')?.addEventListener('click', () => {
    resetInputsToLatest(state.activeState);
    renderSliders();
    updateResult();
  });

  setupReveal();
};

init();
